# kvx.toml — the one that started it all.
# File-to-Elasticsearch. The classic. The original. The OG.
# Like the first pancake — technically works, but mostly a proof of concept.
# 🦆

[runtime]
queue_capacity = 8
sink_parallelism = 8

[source.File]
file_name = "input.json"

[sink.Elasticsearch]
url = "http://localhost:9200"
index = "test-123"

[throttle.source]
max_batch_size_bytes = 131072
max_batch_size_docs = 10000

[throttle.sink]
max_request_size_bytes = 131072
